### ISSUE TITLE
how to post?

### ISSUE THREAD

**Issue by thetuxedo** [Freshwood/akka-http-rest-client#4]
Hi, assume I want to post some data to a rest api

 val respEntity: Future[ByteString] = for {
      request  <- Marshal(postData.getBytes()).to[RequestEntity]
      response <- ClientRequest().withJson.uri(uri).post().map(_.response)
      entity   <- Unmarshal(response.entity).to[ByteString]
    } yield entity

where should I put request in post?

thanks.

**Comment by Freshwood** [comment]
@thetuxedo 
Thank you for your feedback.

This is quite simple to use.
I assume you are using JSON in your project.

So first of all you have to create a request definition.
`val postRequest = ClientRequest().uri("http://localhost:9000/post").withJson.entity(user.toJson.toString)`

After that you can handle the post. In this case you get a predefined user entity back. => Future value
`postRequest.asJson.post[User]`

I have a added a sample inside the test for this case:
https://github.com/Freshwood/akka-http-rest-client/commit/bc27bc4f32de44e1c8162bdacd084a94b52aa928

For ByteString you don't need a json marshaller. In you case:

`val respEntity: Future[ByteString] = ClientRequest().entity(ByteString("Hello World")).withJson.uri("your_url").post[ByteString]`

Greetz

Freshwood

**Comment by thetuxedo** [comment]
thanks a lot for your prompt reply.

It will be good if you can kindly provide more examples in documentation for different use cases. It may seems obvious to you, but for a newbie to akka http like me, it might not.

**Comment by Freshwood** [comment]
@thetuxedo 
Yesterday, I created an issue for a better documentation #5 
So there will be some hints where you can see how to use this lib ;)
