### ISSUE TITLE
tcp idle-timeout

### ISSUE THREAD

**Issue by thetuxedo** [Freshwood/akka-http-rest-client#8]
I encounter an error, sth like "tcp idle-timeout, no bytes pass in last 1 minutes"
I'd like to change it to 3 minutes.
How do I do it using the library?

Or just set the below property in configuration file?
akka.http.client.idle-timeout

Thanks!

**Comment by Freshwood** [comment]
Hi @thetuxedo 
this seems to be a good question.
I will investigate this task further and write a sample so other know what to do.

I will write you back, when I have a good solution for this!

Greetz,

Freshwood

**Comment by Freshwood** [comment]
@thetuxedo 
I just created a little sample which shows how to use this library in an very simple fashion:
https://github.com/Freshwood/akka-http-rest-client/tree/0.2.x/sample/client/src/main

I also created a custom configuration so you can see that your configuration will always be used.
This library takes an implicit actor system from outside, so the user configuration will be used on every request.

Greetz,
Freshwood

**Comment by thetuxedo** [comment]
thanks a million for the prompt action.
